### PR TITLE
c and python Linear Search code algo added

### PR DESCRIPTION
**Pull request by captr1g**

### CODE REVIEW

**Comment by captr1g** [comment]
@MrTwinkleSharma 
@RounakNeogy 
@siddhi-244 
@RishikaGhosh 
@JyotiKumari2 

Please check my PR  :)

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Well done !The python program is good but in c program please add examples

**Review by RishikaGhosh — COMMENTED** [review]
Looks good to me.
The only thing I would have changed is enabling user input instead of hard coding the input.
But if others don't have an issue with that, its fine.
Others please look into this.

**Comment by siddhi-244** [comment]
> Looks good to me.
> The only thing I would have changed is enabling user input instead of hard coding the input.
> But if others don't have an issue with that, its fine.
> Others please look into this.

Yes ,I agree.

**Review by RishikaGhosh — APPROVED** [review]
Looks good to me! Others please give your opinions.

**Comment by RounakNeogy** [comment]
Your code looks fine to me.

**Review by RounakNeogy — APPROVED** [review]

**Comment by captr1g** [comment]
@siddhi-244 
@arpit456jain 
@JyotiKumari2 
@codeaholic-shub 

please check and tell me what to do?

**Review by siddhi-244 — APPROVED** [review]

**Pull request merged**
