### PR TITLE
Add linear search at 01.Searching Algo in c++

### PR DESCRIPTION
**Pull request by captr1g**

### CODE REVIEW

**Comment by codeaholic-shub** [comment]
> _No description provided._

@RounakNeogy 
@siddhi-244 
@RishikaGhosh 
@JyotiKumari2 

Kindly Review this PR !

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Please add the title of the program at the 1st line !

**Comment by siddhi-244** [comment]
> Please add the title of the program at the 1st line !

It would be really helpful for people !

**Review by siddhi-244 — APPROVED** [review]

**Comment by captr1g** [comment]
done add the title on the first line.

**Comment by captr1g** [comment]
now changes approved so my code reflects on the repo or some other processor is left?

**Comment by siddhi-244** [comment]
Wait! Let other people also approve !

**Pull request merged**
